---
title: "Motional-Stark Effect (MSE)"
---


## Introduction

The *Stark Effect* is the shifting and splitting of the electronic energy levels due to an external electric field. The Motional-Stark Effect (MSE), instead, is the specific case in which the electric field is the Lorentz electric field felt by an atom moving in a magnetic field $\mathbf{B}$ at a velocity $\mathbf{v}$, in its rest frame: $\mathbf{E} = \mathbf{v} \times \mathbf{B}$.

In plasma physics, the Motional-Stark Effect (MSE) serves as a crucial diagnostic tool for determining the poloidal magnetic field $\mathbf{B_P}$ within the plasma. Accurate knowledge of the poloidal magnetic field is essential for understanding plasma stability and the formation of Internal Transport Barriers (ITBs). Additionally, MSE measurements enable inference of the plasma current distribution, since the current density $\mathbf{J}$ is related to the magnetic field $\mathbf{B}$ through Ampère's law:

$$
\nabla \times \mathbf{B} = \mu_0 \mathbf{J}.
$$

In TCV, the poloidal magnetic field is determined by the LIUQE (from "EQUIL" spelt backwards) code, which is an equilibrium code based on the resolution of the [Grad-Shafranov equation](../Grad_Shafranov.qmd), and on magnetic probes measurements outside of the plasma. However, when using Neutral Beam Heating (NBH) and Electron Cyclotron Resonance Heating (ECRH), the plasma equilibrium velocity is not negligible anymore, and the magnetic field is locally influenced. This explains the need for the Motional-Stark Effect diagnostic, which provides a direct measurement of the local magnetic field inside the plasma, unaffected by external equilibrium assumptions.


## A bit of history

The Stark effect was discovered by the German physicist Johannes Stark in 1913, for which he was awarded the nobel price in 1919. During the same year the effect was independently discovered by the Italian physicit Antonio Lo Surdo @stark_wikipedia.

## Physical principles


When neutral particles enter in a plasma, they are subject to inelastic collisions with plasma's ions and electrons. The neutrals' electrons, which initially are in their ground state, can reach a higher energy level, $E_{2}$ and, when they decay to a lower energy state $E_{1}$, they emit a photon with energy $E_{\gamma} = E_2 - E_1$, and wavelength $\lambda = \frac{hc}{E_{\gamma}}$. 

In particular, of specific interest is the Balmer-$\alpha$ emission of the deuterium atom $D_{\alpha}$, which corresponds to the transition between $n=3$ and $n=2$, and is characterized by an energy $E_{D_{\alpha}} = 1.89$ eV and a wavelength $\lambda_{D_{\alpha}} = 656.279$ nm.


## On TCV


## References

```{bibliography}