project:
  type: confluence
  output-dir: docs
  title: "Luigi Persico - Ph.D."

format:
  html:
    mathjax:
      macros:
        vect: ["\\boldsymbol{#1}", 1]   # use as \vect{x}
  pdf:
    include-in-header:
      text: |
        \usepackage{amsmath}
        \newcommand{\vect}[1]{\boldsymbol{#1}}

execute:
  freeze: false

bibliography: references.bib
csl: nature-physics.csl